-- Generated by tools/update-plugin-pins.py
-- Do not edit by hand.
--
-- Selection rule:
--   1. latest non-draft, non-prerelease GitHub release older than the cutoff
--   2. otherwise latest Git tag whose resolved commit is older than the cutoff
--   3. otherwise latest default-branch commit older than the cutoff
--
-- commit_only = true means the repository has no usable release/tag pin.

return {
    ["ahmedkhalf/project.nvim"] = {
        commit = "8c6bad7d22eef1b71144b401c9f74ed01526a4fb",
        source = "default-branch:main",
        date = "2023-04-04",
        commit_only = true,
    },
    ["aserowy/tmux.nvim"] = {
        commit = "32ceaf2793582955ef9576809730878c4d2d9426",
        source = "default-branch:main",
        date = "2026-04-13",
        commit_only = true,
    },
    ["benfowler/telescope-luasnip.nvim"] = {
        commit = "07a2a2936a7557404c782dba021ac0a03165b343",
        source = "default-branch:master",
        date = "2024-12-14",
        commit_only = true,
    },
    ["catppuccin/nvim"] = {
        tag = "v2.0.0",
        commit = "605b4603797de970e9f3a4238c199c850da03186",
        source = "release",
        date = "2026-04-02",
    },
    ["danymat/neogen"] = {
        tag = "2.20.0",
        commit = "b2e78708876f4da507839726816010a68e33fec8",
        source = "tag",
        date = "2024-12-27",
    },
    ["glench/vim-jinja2-syntax"] = {
        commit = "2c17843b074b06a835f88587e1023ceff7e2c7d1",
        source = "default-branch:master",
        date = "2021-06-22",
        commit_only = true,
    },
    ["hedyhli/outline.nvim"] = {
        tag = "v1.2.0",
        commit = "ead1820d49c8e79ce89cab1c2c318981b695c9d2",
        source = "release",
        date = "2026-01-31",
    },
    ["honza/vim-snippets"] = {
        tag = "1.0.0",
        commit = "4ed409154bcaa32fba6fd153cc0c915e44982872",
        source = "release",
        date = "2014-05-16",
    },
    ["hrsh7th/cmp-buffer"] = {
        commit = "b74fab3656eea9de20a9b8116afa3cfc4ec09657",
        source = "default-branch:main",
        date = "2025-04-01",
        commit_only = true,
    },
    ["hrsh7th/cmp-cmdline"] = {
        commit = "d126061b624e0af6c3a556428712dd4d4194ec6d",
        source = "default-branch:main",
        date = "2025-05-18",
        commit_only = true,
    },
    ["hrsh7th/cmp-nvim-lsp"] = {
        commit = "cbc7b02bb99fae35cb42f514762b89b5126651ef",
        source = "default-branch:main",
        date = "2025-11-13",
        commit_only = true,
    },
    ["hrsh7th/cmp-omni"] = {
        commit = "4ef610bbd85a5ee4e97e09450c0daecbdc60de86",
        source = "default-branch:main",
        date = "2023-09-24",
        commit_only = true,
    },
    ["hrsh7th/cmp-path"] = {
        commit = "c642487086dbd9a93160e1679a1327be111cbc25",
        source = "default-branch:main",
        date = "2025-07-30",
        commit_only = true,
    },
    ["hrsh7th/nvim-cmp"] = {
        tag = "v0.0.2",
        commit = "8c82d0bd31299dbff7f8e780f5e06d2283de9678",
        source = "release",
        date = "2025-01-07",
    },
    ["iruzo/matrix-nvim"] = {
        commit = "5fafe6b440d08c1070e3c4c4cb9d648436d5d867",
        source = "default-branch:main",
        date = "2023-03-23",
        commit_only = true,
    },
    ["jalvesaq/Nvim-R"] = {
        tag = "v1.0.0",
        commit = "82b570035e5502ac936e9c4cf8b6709469377253",
        source = "release",
        date = "2026-05-02",
    },
    ["junegunn/fzf"] = {
        tag = "v0.73.1",
        commit = "ce4bef75954bebd87e0886435bcf8c6904328ab0",
        source = "release",
        date = "2026-05-25",
    },
    ["junegunn/vim-easy-align"] = {
        tag = "2.10.0",
        commit = "0db4ea6132110631ec678a99a82aa49a0686ae65",
        source = "tag",
        date = "2015-10-01",
    },
    ["kyazdani42/nvim-web-devicons"] = {
        tag = "nerd-v3.2-compat",
        commit = "21417212f640a1dad28a1408f04468819848f5e7",
        source = "tag",
        date = "2024-12-07",
    },
    ["kylechui/nvim-surround"] = {
        tag = "v4.0.5",
        commit = "2e93e154de9ff326def6480a4358bfc149d5da2c",
        source = "release",
        date = "2026-05-02",
    },
    ["L3MON4D3/LuaSnip"] = {
        tag = "v2.5.0",
        commit = "642b0c595e11608b4c18219e93b88d7637af27bc",
        source = "release",
        date = "2026-04-05",
    },
    ["lervag/vimtex"] = {
        tag = "v2.17",
        commit = "2e1bbabeb2c34bb17d7bc8cfdf8f95b16dd0db0c",
        source = "release",
        date = "2025-10-04",
    },
    ["lewis6991/gitsigns.nvim"] = {
        tag = "v2.1.0",
        commit = "a462f416e2ce4744531c6256252dee99a7d34a83",
        source = "release",
        date = "2026-03-26",
    },
    ["lukas-reineke/indent-blankline.nvim"] = {
        tag = "v3.9.1",
        commit = "d28a3f70721c79e3c5f6693057ae929f3d9c0a03",
        source = "release",
        date = "2026-02-17",
    },
    ["mason-org/mason-lspconfig.nvim"] = {
        tag = "v2.2.0",
        commit = "0c2823e0418f3d9230ff8b201c976e84de1cb401",
        source = "release",
        date = "2026-04-23",
    },
    ["mason-org/mason.nvim"] = {
        tag = "v2.3.0",
        commit = "bb639d4bf385a4d89f478b83af4d770be05ab7eb",
        source = "release",
        date = "2026-05-22",
    },
    ["neovim/nvim-lspconfig"] = {
        tag = "v2.9.0",
        commit = "f6738ef65dabade340b473d4ff2a1ad3352c10e7",
        source = "release",
        date = "2026-05-07",
    },
    ["NLKNguyen/papercolor-theme"] = {
        tag = "v1.0",
        commit = "20f1da518d09868bbf3c58ff04f2ae24b1edf23e",
        source = "release",
        date = "2020-12-04",
    },
    ["NvChad/nvim-colorizer.lua"] = {
        commit = "664c0b7cea1de71f8b65dfe951b7996fc3e6ccde",
        source = "default-branch:master",
        date = "2026-05-30",
        commit_only = true,
    },
    ["nvim-lua/plenary.nvim"] = {
        tag = "v0.1.4",
        commit = "50012918b2fc8357b87cff2a7f7f0446e47da174",
        source = "tag",
        date = "2023-10-11",
    },
    ["nvim-lualine/lualine.nvim"] = {
        tag = "compat-nvim-0.6",
        commit = "c55af3b39cc50109aa75d445e38f2089b023e5df",
        source = "tag",
        date = "2023-10-18",
    },
    ["nvim-telescope/telescope-bibtex.nvim"] = {
        commit = "289a6f86ebec06e8ae1590533b732b9981d84900",
        source = "default-branch:master",
        date = "2024-03-28",
        commit_only = true,
    },
    ["nvim-telescope/telescope-file-browser.nvim"] = {
        commit = "3610dc7dc91f06aa98b11dca5cc30dfa98626b7e",
        source = "default-branch:master",
        date = "2025-08-05",
        commit_only = true,
    },
    ["nvim-telescope/telescope-fzf-native.nvim"] = {
        commit = "b25b749b9db64d375d782094e2b9dce53ad53a40",
        source = "default-branch:main",
        date = "2026-05-06",
        commit_only = true,
    },
    ["nvim-telescope/telescope-ui-select.nvim"] = {
        commit = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2",
        source = "default-branch:master",
        date = "2023-12-04",
        commit_only = true,
    },
    ["nvim-telescope/telescope.nvim"] = {
        tag = "v0.2.1",
        commit = "3333a52ff548ba0a68af6d8da1e54f9cd96e9179",
        source = "release",
        date = "2025-12-31",
    },
    ["nvim-treesitter/nvim-treesitter"] = {
        tag = "v0.10.0",
        commit = "42fc28ba918343ebfd5565147a42a26580579482",
        source = "tag",
        date = "2025-05-24",
    },
    ["nvimtools/none-ls.nvim"] = {
        commit = "01f8e62ea11603e59ad9ff7afcfa94fd183f76d6",
        source = "default-branch:main",
        date = "2026-06-02",
        commit_only = true,
    },
    ["onsails/lspkind-nvim"] = {
        commit = "c7274c48137396526b59d86232eabcdc7fed8a32",
        source = "default-branch:master",
        date = "2026-01-29",
        commit_only = true,
    },
    ["petertriho/nvim-scrollbar"] = {
        commit = "f8e87b96cd6362ef8579be456afee3b38fd7e2a8",
        source = "default-branch:main",
        date = "2025-11-17",
        commit_only = true,
    },
    ["rbong/vim-flog"] = {
        tag = "v3.0.0",
        commit = "e7a0e9f6f26d154b1e550de94414ea71e354c563",
        source = "release",
        date = "2024-09-06",
    },
    ["rebelot/kanagawa.nvim"] = {
        commit = "bb85e4bfc8d89b0e62c8fa53ccdd13d12e2f77b3",
        source = "default-branch:master",
        date = "2026-05-10",
        commit_only = true,
    },
    ["saadparwaiz1/cmp_luasnip"] = {
        commit = "98d9cb5c2c38532bd9bdb481067b20fea8f32e90",
        source = "default-branch:master",
        date = "2024-11-04",
        commit_only = true,
    },
    ["sindrets/diffview.nvim"] = {
        commit = "4516612fe98ff56ae0415a259ff6361a89419b0a",
        source = "default-branch:main",
        date = "2024-06-13",
        commit_only = true,
    },
    ["SmiteshP/nvim-navic"] = {
        commit = "f5eba192f39b453675d115351808bd51276d9de5",
        source = "default-branch:master",
        date = "2025-12-29",
        commit_only = true,
    },
    ["stevearc/oil.nvim"] = {
        tag = "v2.16.0",
        commit = "17c0a8faaf48298a0c0cfb0d757c0eaee4ff7a32",
        source = "release",
        date = "2026-05-24",
    },
    ["tools-life/taskwiki"] = {
        tag = "1.0.0",
        commit = "056d9e82f57ee8d897151ff42ce7bc05fa55e7b8",
        source = "tag",
        date = "2019-03-26",
    },
    ["tpope/vim-dispatch"] = {
        tag = "v1.8",
        commit = "488940870ab478cc443b06d5a62fea7ab999eabf",
        source = "tag",
        date = "2019-06-09",
    },
    ["tpope/vim-fugitive"] = {
        tag = "v3.7",
        commit = "96c1009fcf8ce60161cc938d149dd5a66d570756",
        source = "tag",
        date = "2022-06-07",
    },
    ["vim-scripts/a.vim"] = {
        tag = "2.18",
        commit = "2cbe946206ec622d9d8cf2c99317f204c4d41885",
        source = "tag",
        date = "2010-11-06",
    },
    ["vimwiki/vimwiki"] = {
        tag = "v2024.01.24",
        commit = "fde35bb87e45abe930eebef5ab99a16289e53789",
        source = "release",
        date = "2024-01-25",
    },
    ["windwp/nvim-autopairs"] = {
        tag = "0.10.0",
        commit = "23320e75953ac82e559c610bec5a90d9c6dfa743",
        source = "release",
        date = "2025-09-26",
    },
}
