-- require("copilot").setup({
--     panel = {
--         enabled = true,
--         auto_refresh = false,
--         keymap = {
--             jump_prev = "[[",
--             jump_next = "]]",
--             accept = "<CR>",
--             refresh = "gr",
--             open = "<M-CR>",
--         },
--     },
--     suggestion = {
--         enabled = true,
--         auto_trigger = false,
--         debounce = 75,
--         keymap = {
--             accept = "<M-l>",
--             next = "<M-ä>",
--             prev = "<M-ö>",
--             dismiss = "<C-l>",
--         },
--     },
--     filetypes = {
--         yaml = false,
--         markdown = false,
--         help = false,
--         gitcommit = false,
--         gitrebase = false,
--         hgcommit = false,
--         svn = false,
--         cvs = false,
--         ["."] = false,
--     },
--     server_opts_overrides = {},
-- })
