vim.cmd("let g:vimwiki_list = [{ 'path':'~/Notes', 'syntax' : 'markdown', 'ext' : '.md' ,'custom_wiki2html': '~/.local/scripts/vimwiki_convert.py'}]")
vim.cmd("let g:vimwiki_ext2syntax = { '.md':'markdown', '.markdown' : 'markdown', '.mdown' : 'markdown'}")
vim.cmd("let g:taskwiki_markup_syntax = 'markdown'")
vim.cmd("let g:vimwiki_markdown_link_ext = 1")
vim.cmd("let g:taskwiki_disable_concealcorser = 1")
vim.cmd("let g:taskwiki_sort_order='status+,end+,priority+,project+'")
